language: java

sudo: false # faster builds

jdk:
  - openjdk19
  
dist: trusty
  
script: 

  - mvn clean install package
  
  - mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)
